name: Update Daily Discovery List

on:
  schedule:
    - cron: '0 */12 * * *' # Runs every 12 hours
  workflow_dispatch: # Enables manual runs
  
jobs:
  update-daily-discovery:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false  # Disable default token to use PAT explicitly

      - name: Install dependencies
        run: sudo apt-get install -y csvkit

      - name: Prepare Used Movies List
        run: |
          # If previously_used_movies.csv does not exist, create it with headers
          if [ ! -f movies/previously_used_movies.csv ]; then
            echo "title,year,imdb_id,tmdb_id,released,url" > movies/previously_used_movies.csv
          fi

      - name: Check if All Movies Have Been Used
        run: |
          # Count lines in master and previously used lists
          master_count=$(tail -n +2 movies/master_movie_list.csv | wc -l)
          used_count=$(tail -n +2 movies/previously_used_movies.csv | wc -l)
          # If all movies have been used, reset previously_used_movies.csv
          if [ "$master_count" -eq "$used_count" ]; then
            echo "Resetting previously used movies list as all movies have been used."
            echo "title,year,imdb_id,tmdb_id,released,url" > movies/previously_used_movies.csv
          fi

      - name: Select Random Movie Excluding Previously Used Movies
        run: |
          # Clear daily_discovery.csv and add headers
          echo "title,year,imdb_id,tmdb_id,released,url" > movies/daily_discovery.csv
          
          # Select two random movies from master_movie_list.csv excluding previously_used_movies.csv
          selected_movies=$(csvcut -c title,year,imdb_id,tmdb_id,released,url movies/master_movie_list.csv | \
            csvgrep -i -c tmdb_id -f movies/previously_used_movies.csv | \
            shuf -n 2)

          # Log the raw selected_movies output for debugging
          echo "Raw selected movies output:"
          echo "$selected_movies"

          # Check if exactly two movies were selected
          if [ $(echo "$selected_movies" | wc -l) -ne 2 ]; then
            echo "Error: Less than two unique movies available for selection. Skipping this run."
            exit 1
          else
            echo "Selected movies for daily discovery:"
            # Format each selected movie with quotes around each field before appending
            while IFS= read -r line; do
              echo "Processing line: $line"  # Log the line being processed
              
              title=$(echo "$line" | cut -d',' -f1)
              year=$(echo "$line" | cut -d',' -f2)
              imdb_id=$(echo "$line" | cut -d',' -f3)
              tmdb_id=$(echo "$line" | cut -d',' -f4)
              released=$(echo "$line" | cut -d',' -f5)
              url=$(echo "$line" | cut -d',' -f6)

              # Log each parsed field to catch any parsing issues
              echo "  Title: $title"
              echo "  Year: $year"
              echo "  IMDB ID: $imdb_id"
              echo "  TMDB ID: $tmdb_id"
              echo "  Released: $released"
              echo "  URL: $url"
              
              formatted_line="\"$title\",\"$year\",\"$imdb_id\",\"$tmdb_id\",\"$released\",\"$url\""
              echo "$formatted_line" >> movies/daily_discovery.csv
              echo "  - $title"  # Log each movie title being added to daily_discovery.csv
            done <<< "$selected_movies"
          fi

      - name: Append Unique Movies to Previously Used Movies List
        run: |
          # Append only unique entries from daily_discovery.csv to previously_used_movies.csv
          echo "Appending movies to previously_used_movies.csv:"
          while IFS=, read -r title year imdb_id tmdb_id released url; do
            # Check if the tmdb_id already exists in previously_used_movies.csv to prevent duplicates
            if ! grep -q "$tmdb_id" movies/previously_used_movies.csv; then
              echo "$title,$year,$imdb_id,$tmdb_id,$released,$url" >> movies/previously_used_movies.csv
              echo "  - $title"  # Log each movie title being appended to previously_used_movies.csv
            fi
          done < <(tail -n +2 movies/daily_discovery.csv)

      - name: Format Previously Used Movies List
        run: |
          # Add header manually to a new temporary file
          echo "title,year,imdb_id,tmdb_id,released,url" > movies/previously_used_movies_temp.csv

          # Format the data rows and append them to the new file
          tail -n +2 movies/previously_used_movies.csv | csvformat -U 1 -T >> movies/previously_used_movies_temp.csv

          # Replace the original file with the formatted one
          mv movies/previously_used_movies_temp.csv movies/previously_used_movies.csv

      - name: Commit and push changes
        env:
          DAILY_DISCOVERY_PAT: ${{ secrets.DAILY_DISCOVERY_PAT }}
        run: |
          git config --local user.email "you@example.com"
          git config --local user.name "GitHub Actions"
          git remote set-url origin https://$DAILY_DISCOVERY_PAT@github.com/ThatMovieGuyOriginal/movie-feeds.git
          git add movies/daily_discovery.csv movies/previously_used_movies.csv
          git commit -m "Update free movies for RSS feed and log used movie"
          git push origin main
